resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 3s
    instances:
      categoryBreaker:
        base-config: default
      dietBreaker:
        base-config: default
      ingredientBreaker:
        base-config: default
      macronutrientBreaker:
        base-config: default
      pantryBreaker:
        base-config: default
      recipeBreaker:
        base-config: default
      subcategoryBreaker:
        base-config: default
      typeIngredientBreaker:
        base-config: default
      variantIngredientBreaker:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
    instances:
      categoryBreaker:
        base-config: default
      dietBreaker:
        base-config: default
      ingredientBreaker:
        base-config: default
      macronutrientBreaker:
        base-config: default
      pantryBreaker:
        base-config: default
      recipeBreaker:
        base-config: default
      subcategoryBreaker:
        base-config: default
      typeIngredientBreaker:
        base-config: default
      variantIngredientBreaker:
        base-config: default